import tkinter as tk
root = tk.Tk()
root.title("Layouts")
root.geometry("500x400")
frame_pack = tk.Frame(root, bg="darkblue")
frame_pack.pack(fill="both", expand=True)
label1=tk.Label(frame_pack, text="PACK Layout", bg="lightblue", font=("Arial", 14))
label1.pack()
btn1=tk.Button(frame_pack, text="Button 1")
btn1.pack(side=tk.LEFT, padx=10, pady=10)
btn2=tk.Button(frame_pack, text="Button 2")
btn2.pack(side=tk.LEFT, padx=10, pady=10
btn3=tk.Button(frame_pack, text="Button 3")
btn3.pack(side=tk.LEFT, padx=10, pady=10)
frame_grid = tk.Frame(root, bg="purple")
frame_grid.pack(fill="both", expand=True)
label2=tk.Label(frame_grid, text="GRID Layout", bg="pink", font=("Arial", 14))
label2.grid(row=0, column=0, columnspan=2)
label3=tk.Label(frame_grid, text="Username")
label3.grid(row=1, column=0)
entry1=tk.Entry(frame_grid)
entry1.grid(row=1, column=1)
label4=tk.Label(frame_grid, text="Password")
label4.grid(row=2, column=0)
entry2=tk.Entry(frame_grid, show="*")
entry2.grid(row=2, column=1)
btn4=tk.Button(frame_grid, text="Login")
frame_place = tk.Frame(root, bg="red", height=120)
frame_place.pack(fill="both", expand=True)
label5=tk.Label(frame_place, text="PLACE Layout", fg="black",bg="yellow", font=("Arial",
14))
label5.place(x=180, y=10)
btn5=tk.Button(frame_place, text="OK")
btn5.place(x=150, y=50)
btn6=tk.Button(frame_place, text="Cancel")
btn6.place(x=250, y=50)
root.mainloop()
